version: '3'

services:
  php: 
    build: ./docker/php
    container_name: php_laravel
    volumes:
      - ./src:/var/www/html

  apache:
    build: ./docker/apache
    container_name: apache_laravel
    volumes: 
      - ./src:/var/www/html
    ports:
      - 8080:80
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    container_name: db_laravel
    volumes:
      - ./docker/db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db_laravel
      PMA_PORT: 3306
    ports:
      - 8181:80
    depends_on: 
      - db

    